on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - release/*
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: philips-software/sonar-scanner-action@v1.5.0
      env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.SONAR_TOKEN }}
        baseDir: .
        enablePullRequestDecoration: true
