on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, merged]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
        sudo apt-get update -y
        sudo apt-get install unzip
        sudo unzip sonar-scanner-cli-4.7.0.2747-linux.zip
        sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
        export PATH=$PATH:/opt/sonar-scanner/bin
        sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=idfsbank -Dsonar.organization=atulyw